# Spring properties
spring:
  # Thymeleaf properties
  thymeleaf:
    cache: false

  # Messages properties
  messages:
    basename: bundles/messages
    encoding: iso-8859-1

  # Datasource properties
  datasource:
    url: jdbc:mysql://localhost:3306/db_itest?autoReconnect=true&useSSL=false
    username: root
    data-username: root
    password: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver

  # JPA properties
  jpa:
    show-sql: true
    hibernate:
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  # Mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: user@gmail.com
    password: password
    properties:
      mail:
        smtp:
          starttls:
            enabled: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000